insert into authors (id, first_name, last_name) values (1, 'Willabella', 'McGinly');
insert into authors (id, first_name, last_name) values (2, 'Margarete', 'Haycox');
insert into authors (id, first_name, last_name) values (3, 'Whitney', 'Portriss');
insert into authors (id, first_name, last_name) values (4, 'Lem', 'Hayen');
insert into authors (id, first_name, last_name) values (5, 'Car', 'Fritzer');
insert into authors (id, first_name, last_name) values (6, 'Lise', 'Kiss');
insert into authors (id, first_name, last_name) values (7, 'Hillary', 'Basezzi');
insert into authors (id, first_name, last_name) values (8, 'Skye', 'Redbourn');
insert into authors (id, first_name, last_name) values (9, 'Danit', 'Olivelli');
insert into authors (id, first_name, last_name) values (10, 'Kitty', 'Dormer');
insert into authors (id, first_name, last_name) values (11, 'Ardith', 'Assinder');
insert into authors (id, first_name, last_name) values (12, 'Urson', 'Matessian');
insert into authors (id, first_name, last_name) values (13, 'Alva', 'Dewes');
insert into authors (id, first_name, last_name) values (14, 'Anny', 'Phlippsen');
insert into authors (id, first_name, last_name) values (15, 'Virgie', 'Rubinsohn');
insert into authors (id, first_name, last_name) values (16, 'Alfred', 'Melsom');
insert into authors (id, first_name, last_name) values (17, 'Fara', 'Gillingwater');
insert into authors (id, first_name, last_name) values (18, 'Judd', 'Allison');
insert into authors (id, first_name, last_name) values (19, 'Rania', 'Senter');
insert into authors (id, first_name, last_name) values (20, 'Loutitia', 'Alstead');
insert into authors (id, first_name, last_name) values (21, 'Neville', 'Berresford');
insert into authors (id, first_name, last_name) values (22, 'Sherie', 'Mahoney');
insert into authors (id, first_name, last_name) values (23, 'Sheilah', 'Tomik');
insert into authors (id, first_name, last_name) values (24, 'Vidovic', 'Cattle');
insert into authors (id, first_name, last_name) values (25, 'Madlin', 'Stoffer');
insert into authors (id, first_name, last_name) values (26, 'Olivia', 'Ramshay');
insert into authors (id, first_name, last_name) values (27, 'Udall', 'Dormer');
insert into authors (id, first_name, last_name) values (28, 'Etta', 'Stockford');
insert into authors (id, first_name, last_name) values (29, 'Joel', 'Lampens');
insert into authors (id, first_name, last_name) values (30, 'Alikee', 'Bickley');
insert into authors (id, first_name, last_name) values (31, 'Merralee', 'Lait');
insert into authors (id, first_name, last_name) values (32, 'Aleen', 'Osment');
insert into authors (id, first_name, last_name) values (33, 'Jodee', 'Ravenscroftt');
insert into authors (id, first_name, last_name) values (34, 'Therine', 'Danielsen');
insert into authors (id, first_name, last_name) values (35, 'Adel', 'Janaway');
insert into authors (id, first_name, last_name) values (36, 'Massimo', 'Cayzer');
insert into authors (id, first_name, last_name) values (37, 'Angela', 'Peotz');
insert into authors (id, first_name, last_name) values (38, 'Boonie', 'Douch');
insert into authors (id, first_name, last_name) values (39, 'Rachael', 'Blundon');
insert into authors (id, first_name, last_name) values (40, 'Claudetta', 'Hoffmann');
insert into authors (id, first_name, last_name) values (41, 'Emera', 'Stefi');
insert into authors (id, first_name, last_name) values (42, 'Dietrich', 'McKague');
insert into authors (id, first_name, last_name) values (43, 'Sammie', 'Simonnin');
insert into authors (id, first_name, last_name) values (44, 'Jamaal', 'Soeiro');
insert into authors (id, first_name, last_name) values (45, 'Glyn', 'Lippiett');
insert into authors (id, first_name, last_name) values (46, 'Lamont', 'Labdon');
insert into authors (id, first_name, last_name) values (47, 'Regine', 'Dumingo');
insert into authors (id, first_name, last_name) values (48, 'Therese', 'Wheatley');
insert into authors (id, first_name, last_name) values (49, 'Richie', 'Newlands');
insert into authors (id, first_name, last_name) values (50, 'Isadora', 'Waszczykowski');
insert into authors (id, first_name, last_name) values (51, 'Karmen', 'Maleham');
insert into authors (id, first_name, last_name) values (52, 'Arne', 'Smither');
insert into authors (id, first_name, last_name) values (53, 'Gino', 'Hartless');
insert into authors (id, first_name, last_name) values (54, 'Saxon', 'Keynd');
insert into authors (id, first_name, last_name) values (55, 'Tova', 'Carlile');
insert into authors (id, first_name, last_name) values (56, 'Rowena', 'Barabich');
insert into authors (id, first_name, last_name) values (57, 'Evyn', 'Roscamps');
insert into authors (id, first_name, last_name) values (58, 'Hoebart', 'Cockland');
insert into authors (id, first_name, last_name) values (59, 'Bibbie', 'McSharry');
insert into authors (id, first_name, last_name) values (60, 'Vickie', 'Tringham');
insert into authors (id, first_name, last_name) values (61, 'Sherman', 'Dugood');
insert into authors (id, first_name, last_name) values (62, 'Alameda', 'Sheaf');
insert into authors (id, first_name, last_name) values (63, 'Helge', 'Luc');
insert into authors (id, first_name, last_name) values (64, 'Donn', 'Orable');
insert into authors (id, first_name, last_name) values (65, 'Cacilia', 'Haccleton');
insert into authors (id, first_name, last_name) values (66, 'Adaline', 'Gaddie');
insert into authors (id, first_name, last_name) values (67, 'Shirleen', 'Gamage');
insert into authors (id, first_name, last_name) values (68, 'Livia', 'Bayly');
insert into authors (id, first_name, last_name) values (69, 'Ken', 'Dukesbury');
insert into authors (id, first_name, last_name) values (70, 'Paulie', 'Prene');
insert into authors (id, first_name, last_name) values (71, 'Cher', 'Grumble');
insert into authors (id, first_name, last_name) values (72, 'Vilma', 'Satchell');
insert into authors (id, first_name, last_name) values (73, 'Stephenie', 'Timperley');
insert into authors (id, first_name, last_name) values (74, 'Timmie', 'Doggerell');
insert into authors (id, first_name, last_name) values (75, 'Sabrina', 'Beckinsale');
insert into authors (id, first_name, last_name) values (76, 'Sydelle', 'Khoter');
insert into authors (id, first_name, last_name) values (77, 'Anne-marie', 'Wem');
insert into authors (id, first_name, last_name) values (78, 'Devonna', 'Bendon');
insert into authors (id, first_name, last_name) values (79, 'Arri', 'Corsor');
insert into authors (id, first_name, last_name) values (80, 'Karrie', 'Miskimmon');
insert into authors (id, first_name, last_name) values (81, 'Westley', 'Vosse');
insert into authors (id, first_name, last_name) values (82, 'Donovan', 'Woodfield');
insert into authors (id, first_name, last_name) values (83, 'Granny', 'Bosley');
insert into authors (id, first_name, last_name) values (84, 'Pearce', 'Keave');
insert into authors (id, first_name, last_name) values (85, 'Rancell', 'Collens');
insert into authors (id, first_name, last_name) values (86, 'Rosaline', 'Roberts');
insert into authors (id, first_name, last_name) values (87, 'Debi', 'Twallin');
insert into authors (id, first_name, last_name) values (88, 'Crosby', 'Gaskins');
insert into authors (id, first_name, last_name) values (89, 'Nickolaus', 'Kitteringham');
insert into authors (id, first_name, last_name) values (90, 'Hadria', 'Bartlomieczak');
insert into authors (id, first_name, last_name) values (91, 'Danette', 'Breslau');
insert into authors (id, first_name, last_name) values (92, 'Daron', 'O Donohue');
insert into authors (id, first_name, last_name) values (93, 'Rudolf', 'Philippart');
insert into authors (id, first_name, last_name) values (94, 'Wynny', 'Cornforth');
insert into authors (id, first_name, last_name) values (95, 'Frederica', 'Marchant');
insert into authors (id, first_name, last_name) values (96, 'Carolann', 'Chaudret');
insert into authors (id, first_name, last_name) values (97, 'Sascha', 'Course');
insert into authors (id, first_name, last_name) values (98, 'Olympe', 'Charette');
insert into authors (id, first_name, last_name) values (99, 'Hedvige', 'Tampen');
insert into authors (id, first_name, last_name) values (100, 'Maggie', 'Asbury');

insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (1, '4/4/2021', 19, 'http://dummyimage.com/195x100.png/dddddd/000000', 'Little Dieter Needs to Fly', 'innovate open-source functionalities', 2514, 3591, 91);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (2, '12/13/2021', 90, 'http://dummyimage.com/183x100.png/dddddd/000000', 'Battlestar Galactica: Razor', 'syndicate clicks-and-mortar action-items', 1851, 3210, 18);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (3, '12/3/2021', 50, 'http://dummyimage.com/181x100.png/dddddd/000000', 'Protector, The', 'reintermediate frictionless communities', 1918, 2464, 19);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (4, '3/20/2021', 34, 'http://dummyimage.com/145x100.png/5fa2dd/ffffff', 'Great King, The (Der gro?e K?nig)', 'iterate 24/365 methodologies', 1951, 3578, 56);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (5, '7/27/2021', 83, 'http://dummyimage.com/207x100.png/dddddd/000000', 'Body of Water (Syv?lle salattu)', 'scale cross-media infomediaries', 2077, 3826, 81);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (6, '2/11/2021', 61, 'http://dummyimage.com/131x100.png/ff4444/ffffff', 'Bongwater', 'enhance revolutionary e-services', 1185, 2723, 86);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (7, '3/19/2021', 81, 'http://dummyimage.com/174x100.png/5fa2dd/ffffff', 'Achilles and the Tortoise (Akiresu to kame)', 'evolve 24/365 mindshare', 1677, 4070, 28);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (8, '3/2/2021', 18, 'http://dummyimage.com/167x100.png/ff4444/ffffff', 'Brood, The', 'seize clicks-and-mortar niches', 1311, 3416, 61);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (9, '6/10/2021', 1, 'http://dummyimage.com/167x100.png/cc0000/ffffff', 'Xuxa in Crystal Moon', 'engage innovative architectures', 2803, 3613, 65);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (10, '12/13/2021', 47, 'http://dummyimage.com/121x100.png/cc0000/ffffff', 'Vanishing Point', 'empower holistic functionalities', 1350, 2744, 83);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (11, '3/3/2021', 2, 'http://dummyimage.com/106x100.png/ff4444/ffffff', 'Three Monkeys (?? maymun)', 'reintermediate global infomediaries', 1462, 4653, 25);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (12, '9/16/2021', 51, 'http://dummyimage.com/196x100.png/ff4444/ffffff', 'Jewel Robbery', 'streamline killer portals', 1047, 2284, 77);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (13, '11/23/2021', 80, 'http://dummyimage.com/194x100.png/5fa2dd/ffffff', 'Girl Who Played with Fire, The (Flickan som lekte med elden)', 'engineer dot-com e-business', 2147, 3993, 66);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (14, '10/1/2021', 40, 'http://dummyimage.com/119x100.png/cc0000/ffffff', 'When Jews Were Funny', 'integrate global supply-chains', 2847, 2276, 16);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (15, '3/19/2021', 28, 'http://dummyimage.com/246x100.png/dddddd/000000', 'I Hate Valentine''s Day', 'leverage integrated niches', 2219, 4597, 29);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (16, '7/22/2021', 37, 'http://dummyimage.com/163x100.png/dddddd/000000', 'Bizarre, Bizarre (Dr?le de drame ou L''?trange aventure de Docteur Molyneux)', 'iterate open-source supply-chains', 2943, 3623, 40);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (17, '9/24/2021', 58, 'http://dummyimage.com/151x100.png/dddddd/000000', 'Naked Civil Servant, The', 'revolutionize impactful infomediaries', 1583, 3870, 87);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (18, '9/27/2021', 54, 'http://dummyimage.com/156x100.png/cc0000/ffffff', 'Kissed by Winter (Vinterkyss)', 'productize efficient niches', 1302, 2859, 73);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (19, '3/9/2021', 11, 'http://dummyimage.com/129x100.png/ff4444/ffffff', 'Blood and Sand', 'reinvent wireless channels', 2726, 4915, 68);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (20, '2/12/2021', 18, 'http://dummyimage.com/159x100.png/cc0000/ffffff', 'Brooklyn''s Finest', 'transition ubiquitous relationships', 2537, 2491, 74);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (21, '5/24/2021', 8, 'http://dummyimage.com/146x100.png/5fa2dd/ffffff', 'Panda! Go Panda! Rainy Day Circus', 'reinvent ubiquitous markets', 1248, 3796, 52);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (22, '11/21/2021', 22, 'http://dummyimage.com/189x100.png/5fa2dd/ffffff', 'Reggie Watts: Why Shit So Crazy?', 'streamline open-source functionalities', 1877, 3032, 83);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (23, '7/14/2021', 29, 'http://dummyimage.com/101x100.png/5fa2dd/ffffff', 'Death of the Incredible Hulk, The', 'visualize value-added e-business', 2088, 4916, 6);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (24, '9/24/2021', 91, 'http://dummyimage.com/152x100.png/cc0000/ffffff', 'Mr. Jealousy', 'mesh customized models', 1857, 3795, 42);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (25, '12/27/2021', 10, 'http://dummyimage.com/156x100.png/dddddd/000000', 'Midsummer Night''s Dream, A', 'revolutionize vertical web services', 1266, 4195, 34);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (26, '3/10/2021', 98, 'http://dummyimage.com/219x100.png/cc0000/ffffff', 'I Want You', 'revolutionize frictionless solutions', 2308, 3990, 84);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (27, '8/28/2021', 57, 'http://dummyimage.com/101x100.png/cc0000/ffffff', 'Wankers, The (Les branleuses)', 'aggregate B2B functionalities', 2393, 4198, 86);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (28, '10/6/2021', 15, 'http://dummyimage.com/156x100.png/dddddd/000000', 'Kill! (Kiru)', 'reintermediate innovative networks', 1700, 4888, 43);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (29, '11/3/2021', 50, 'http://dummyimage.com/112x100.png/dddddd/000000', 'Accattone', 'repurpose B2C e-commerce', 2901, 2000, 6);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (30, '8/27/2021', 92, 'http://dummyimage.com/154x100.png/dddddd/000000', 'American Promise', 'empower front-end e-markets', 1863, 4907, 82);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (31, '12/11/2021', 24, 'http://dummyimage.com/169x100.png/dddddd/000000', 'Crossworlds', 'repurpose visionary interfaces', 1810, 3599, 74);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (32, '7/30/2021', 42, 'http://dummyimage.com/171x100.png/ff4444/ffffff', 'Blink', 'repurpose B2B systems', 1823, 4602, 80);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (33, '6/22/2021', 39, 'http://dummyimage.com/153x100.png/cc0000/ffffff', 'Miracle Woman, The', 'deploy ubiquitous paradigms', 2849, 4615, 30);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (34, '5/27/2021', 69, 'http://dummyimage.com/136x100.png/dddddd/000000', 'Kung Fu Panda 2', 'orchestrate impactful content', 1212, 2767, 45);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (35, '1/28/2021', 56, 'http://dummyimage.com/186x100.png/dddddd/000000', 'Turkish Delight (Turks fruit)', 'mesh virtual architectures', 2849, 3492, 31);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (36, '7/16/2021', 67, 'http://dummyimage.com/121x100.png/cc0000/ffffff', 'Revenge of the Green Dragons', 'synergize sticky e-markets', 2417, 4667, 20);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (37, '6/25/2021', 42, 'http://dummyimage.com/200x100.png/dddddd/000000', 'At First Sight', 'innovate collaborative mindshare', 1667, 2717, 74);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (38, '8/24/2021', 15, 'http://dummyimage.com/224x100.png/5fa2dd/ffffff', 'Monty Python''s The Meaning of Life', 'cultivate intuitive action-items', 1476, 2373, 22);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (39, '11/11/2021', 58, 'http://dummyimage.com/220x100.png/ff4444/ffffff', 'Everybody Wants to Be Italian', 'reinvent efficient models', 2260, 3195, 19);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (40, '7/28/2021', 1, 'http://dummyimage.com/132x100.png/dddddd/000000', 'Monsters University', 'brand impactful platforms', 1486, 3470, 68);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (41, '10/24/2021', 95, 'http://dummyimage.com/186x100.png/dddddd/000000', 'Black', 'mesh mission-critical synergies', 2384, 3042, 89);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (42, '4/21/2021', 66, 'http://dummyimage.com/172x100.png/ff4444/ffffff', 'Price of Forgiveness, The (Ndeysaan)', 'recontextualize enterprise eyeballs', 2177, 3028, 62);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (43, '1/19/2021', 67, 'http://dummyimage.com/108x100.png/cc0000/ffffff', 'Black Ice (Musta j??)', 'enhance next-generation niches', 1398, 2886, 21);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (44, '11/25/2021', 23, 'http://dummyimage.com/163x100.png/ff4444/ffffff', 'One Man''s Hero', 'target bricks-and-clicks web services', 2016, 2899, 24);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (45, '6/5/2021', 91, 'http://dummyimage.com/244x100.png/ff4444/ffffff', 'White Darkness, The', 'unleash out-of-the-box systems', 1337, 2916, 51);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (46, '5/19/2021', 90, 'http://dummyimage.com/106x100.png/dddddd/000000', 'Osterman Weekend, The', 'morph 24/365 niches', 1477, 3681, 53);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (47, '10/24/2021', 89, 'http://dummyimage.com/245x100.png/ff4444/ffffff', 'Thompsons, The', 'disintermediate synergistic infomediaries', 1136, 4467, 66);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (48, '8/18/2021', 67, 'http://dummyimage.com/247x100.png/5fa2dd/ffffff', 'I Am a Sex Addict', 'strategize user-centric niches', 1841, 2160, 60);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (49, '4/1/2021', 22, 'http://dummyimage.com/143x100.png/cc0000/ffffff', 'A Thousand Times Goodnight', 'target open-source models', 1377, 4130, 48);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (50, '2/19/2021', 2, 'http://dummyimage.com/108x100.png/5fa2dd/ffffff', 'Sons of Katie Elder', 'syndicate enterprise portals', 1206, 3059, 41);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (51, '6/7/2021', 81, 'http://dummyimage.com/224x100.png/ff4444/ffffff', 'Bunnyman', 'repurpose revolutionary solutions', 1174, 4991, 63);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (52, '6/30/2021', 57, 'http://dummyimage.com/221x100.png/5fa2dd/ffffff', 'Glumov''s Diary (Dnevnik Glumova)', 'benchmark synergistic channels', 1046, 4842, 1);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (53, '11/26/2021', 27, 'http://dummyimage.com/152x100.png/5fa2dd/ffffff', 'Death Sentence', 'mesh front-end solutions', 1785, 3595, 17);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (54, '3/14/2021', 89, 'http://dummyimage.com/111x100.png/ff4444/ffffff', 'Silent Sonata', 'optimize open-source action-items', 1167, 3953, 73);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (55, '9/11/2021', 4, 'http://dummyimage.com/110x100.png/dddddd/000000', 'Ten Minutes Older: The Trumpet', 'e-enable real-time e-business', 1803, 4830, 49);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (56, '5/7/2021', 55, 'http://dummyimage.com/193x100.png/dddddd/000000', 'Dr. No', 'leverage bricks-and-clicks networks', 1761, 3460, 54);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (57, '5/5/2021', 42, 'http://dummyimage.com/122x100.png/dddddd/000000', 'Chasing Ice', 'transform holistic functionalities', 1100, 4520, 75);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (58, '7/20/2021', 51, 'http://dummyimage.com/176x100.png/5fa2dd/ffffff', 'American Dreamz', 'revolutionize web-enabled experiences', 2346, 2175, 74);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (59, '10/11/2021', 1, 'http://dummyimage.com/108x100.png/cc0000/ffffff', 'Paths of Hate', 'synergize holistic relationships', 1192, 3028, 10);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (60, '12/23/2021', 7, 'http://dummyimage.com/176x100.png/dddddd/000000', 'Book of Shadows: Blair Witch 2', 'iterate next-generation technologies', 2600, 4796, 22);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (61, '2/1/2021', 68, 'http://dummyimage.com/126x100.png/cc0000/ffffff', 'Katt Williams: The Pimp Chronicles Pt. 1', 'deploy bleeding-edge interfaces', 1344, 3249, 91);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (62, '12/27/2021', 62, 'http://dummyimage.com/171x100.png/ff4444/ffffff', 'Serving Life', 'deploy user-centric technologies', 1100, 4028, 24);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (63, '3/11/2021', 25, 'http://dummyimage.com/246x100.png/dddddd/000000', 'Comrades: Almost a Love Story (Tian mi mi)', 'morph robust paradigms', 2296, 4244, 24);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (64, '8/20/2021', 4, 'http://dummyimage.com/208x100.png/5fa2dd/ffffff', 'Living on One Dollar', 'engage efficient communities', 2930, 3505, 70);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (65, '11/20/2021', 67, 'http://dummyimage.com/138x100.png/ff4444/ffffff', 'Detective (D?tective)', 'visualize bricks-and-clicks web services', 2583, 2910, 62);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (66, '12/13/2021', 70, 'http://dummyimage.com/184x100.png/5fa2dd/ffffff', 'Samurai Banners (F?rin kazan)', 'implement scalable synergies', 2827, 3224, 14);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (67, '4/6/2021', 83, 'http://dummyimage.com/192x100.png/cc0000/ffffff', 'Murderball', 'incentivize 24/7 methodologies', 1445, 3902, 10);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (68, '10/19/2021', 37, 'http://dummyimage.com/160x100.png/dddddd/000000', 'Divorce of Lady X, The', 'unleash world-class interfaces', 2747, 4442, 57);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (69, '11/27/2021', 10, 'http://dummyimage.com/174x100.png/dddddd/000000', 'Key Largo', 'facilitate proactive technologies', 2915, 3428, 43);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (70, '9/17/2021', 54, 'http://dummyimage.com/189x100.png/5fa2dd/ffffff', 'Flock, The', 'iterate intuitive bandwidth', 2207, 2351, 27);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (71, '3/11/2021', 46, 'http://dummyimage.com/183x100.png/5fa2dd/ffffff', 'Shanghai Kiss', 'monetize front-end infomediaries', 1480, 2013, 32);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (72, '1/13/2022', 71, 'http://dummyimage.com/136x100.png/ff4444/ffffff', 'Big Eyes', 'transform viral infrastructures', 1222, 4954, 55);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (73, '3/12/2021', 4, 'http://dummyimage.com/102x100.png/dddddd/000000', 'Clue', 'incubate cross-platform technologies', 2216, 3636, 17);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (74, '1/17/2021', 92, 'http://dummyimage.com/208x100.png/dddddd/000000', 'Black Cauldron, The', 'disintermediate cross-platform markets', 2265, 4322, 45);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (75, '1/15/2022', 62, 'http://dummyimage.com/225x100.png/5fa2dd/ffffff', 'Boy Wonder', 'mesh ubiquitous e-business', 1231, 3464, 15);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (76, '6/10/2021', 34, 'http://dummyimage.com/161x100.png/5fa2dd/ffffff', 'Corbeau, Le (Raven, The)', 'expedite enterprise e-commerce', 2394, 2387, 63);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (77, '4/4/2021', 41, 'http://dummyimage.com/199x100.png/cc0000/ffffff', 'In the Winter Dark', 'unleash strategic channels', 2782, 2036, 6);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (78, '11/4/2021', 82, 'http://dummyimage.com/105x100.png/ff4444/ffffff', 'Citizen Kane', 'incentivize sticky supply-chains', 2072, 3780, 11);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (79, '6/14/2021', 35, 'http://dummyimage.com/202x100.png/cc0000/ffffff', 'King of Texas, The', 'envisioneer cross-media infomediaries', 1713, 3213, 8);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (80, '12/31/2021', 62, 'http://dummyimage.com/204x100.png/5fa2dd/ffffff', 'Looking for Eric', 'implement best-of-breed networks', 2102, 2772, 63);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (81, '8/12/2021', 34, 'http://dummyimage.com/151x100.png/dddddd/000000', 'Cat in the Hat, The', 'repurpose compelling niches', 2604, 2488, 35);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (82, '4/13/2021', 75, 'http://dummyimage.com/168x100.png/5fa2dd/ffffff', 'Iron Eagle IV', 'extend ubiquitous eyeballs', 1564, 4746, 53);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (83, '11/14/2021', 22, 'http://dummyimage.com/129x100.png/dddddd/000000', 'Love Hina Christmas Special: Silent Eve (Rabu Hina kurisumasu supesharu: Sairento ivu)', 'e-enable web-enabled ROI', 1992, 3994, 85);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (84, '3/19/2021', 36, 'http://dummyimage.com/175x100.png/cc0000/ffffff', 'Ladybug Ladybug ', 'facilitate mission-critical solutions', 1966, 2914, 51);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (85, '4/12/2021', 30, 'http://dummyimage.com/187x100.png/dddddd/000000', 'Forest of Bliss', 'transition killer users', 1752, 3522, 73);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (86, '8/18/2021', 19, 'http://dummyimage.com/103x100.png/cc0000/ffffff', 'Fever in the Blood, A', 'implement customized e-markets', 1418, 4826, 47);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (87, '7/12/2021', 56, 'http://dummyimage.com/115x100.png/5fa2dd/ffffff', 'Sex Tape', 'drive bleeding-edge action-items', 1468, 4717, 17);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (88, '4/10/2021', 89, 'http://dummyimage.com/123x100.png/dddddd/000000', 'Take Care of Your Scarf, Tatiana (Pid? huivista kiinni, Tatjana)', 'target clicks-and-mortar interfaces', 2052, 3957, 61);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (89, '3/21/2021', 17, 'http://dummyimage.com/220x100.png/cc0000/ffffff', 'Blackwoods', 'brand compelling infrastructures', 2782, 3140, 52);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (90, '10/7/2021', 53, 'http://dummyimage.com/111x100.png/dddddd/000000', 'Sleeping Dictionary, The', 'incentivize user-centric partnerships', 2802, 2659, 77);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (91, '7/24/2021', 3, 'http://dummyimage.com/120x100.png/5fa2dd/ffffff', 'Phil Ochs: There But for Fortune', 'deploy innovative e-tailers', 1258, 2876, 76);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (92, '4/15/2021', 93, 'http://dummyimage.com/162x100.png/5fa2dd/ffffff', 'Zardoz', 'scale interactive bandwidth', 2898, 2414, 71);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (93, '9/2/2021', 96, 'http://dummyimage.com/214x100.png/dddddd/000000', 'Better Way to Die, A', 'synthesize enterprise supply-chains', 1299, 2965, 70);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (94, '7/27/2021', 95, 'http://dummyimage.com/114x100.png/ff4444/ffffff', 'Escape From Tomorrow', 'unleash extensible methodologies', 1054, 3328, 22);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (95, '5/3/2021', 30, 'http://dummyimage.com/118x100.png/cc0000/ffffff', 'From Dusk Till Dawn 2: Texas Blood Money ', 'evolve plug-and-play applications', 1622, 3689, 44);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (96, '2/11/2021', 5, 'http://dummyimage.com/105x100.png/cc0000/ffffff', 'Intern, The', 'cultivate bleeding-edge eyeballs', 2236, 3343, 5);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (97, '8/8/2021', 36, 'http://dummyimage.com/227x100.png/5fa2dd/ffffff', 'Delirious', 'incubate cutting-edge applications', 2452, 3402, 40);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (98, '4/15/2021', 69, 'http://dummyimage.com/141x100.png/dddddd/000000', 'Brewster''s Millions', 'empower dynamic experiences', 1256, 4790, 81);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (99, '8/2/2021', 30, 'http://dummyimage.com/155x100.png/dddddd/000000', 'Just Like Heaven', 'recontextualize viral e-tailers', 2409, 3917, 42);
insert into books (id, pub_date, is_bestseller, image, title, description, price, price_old, author_id) values (100, '10/17/2021', 39, 'http://dummyimage.com/212x100.png/cc0000/ffffff', 'Paul Williams Still Alive', 'disintermediate revolutionary bandwidth', 1698, 3636, 42);
