apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bookshop.service.name }}
  labels:
    spring-boot: "true"
spec:
  selector:
    app: {{ .Values.bookshop.name }}
  ports:
    - port: {{ .Values.bookshop.container.port }}
      targetPort: {{ .Values.bookshop.container.port }}
  type: ClusterIP
