apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bookshop.name }}
spec:
  replicas: {{ .Values.bookshop.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.bookshop.name }}
  template:
    metadata:
      name: {{ .Values.bookshop.name }}
      labels:
        app: {{ .Values.bookshop.name }}
    spec:
      containers:
      - name: {{ .Values.bookshop.name }}
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.bookshop.postgres.secret.name }}
                key: {{ .Values.bookshop.postgres.secret.key.user }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.bookshop.postgres.secret.name }}
                key: {{ .Values.bookshop.postgres.secret.key.password }}
          - name: POSTGRES_HOST
            value: {{ .Values.bookshop.postgres.host }}
          - name: ADMIN_URL
            value: {{ .Values.bookshop.admin.host }}
          - name: BASE_URL
            value: {{ .Values.bookshop.ingress.host }}
        image: {{ .Values.bookshop.container.image }}
      imagePullSecrets:
      - name: gitlab-credential
